In [38]:
import pandas as pd
pd.read_excel('nba_xlsx.xlsx')

                      Team   W    PTS   FG%   FT%   REB   AST   TOV   STL  BLK
0          Milwaukee Bucks  55  118.7  47.8  74.5  51.8  25.9  15.1   7.3  6.0
1       Los Angeles Lakers  51  113.2  47.9  73.0  45.9  25.4  15.2   8.6  6.7
2          Toronto Raptors  49  112.7  45.8  80.3  45.2  25.3  14.6   8.7  4.9
3              LA Clippers  46  116.2  46.5  79.2  47.7  23.7  14.6   7.0  4.9
4           Boston Celtics  45  113.6  46.1  80.1  45.8  22.7  13.7   8.3  5.6
5           Denver Nuggets  45  110.9  47.2  77.6  44.2  26.6  13.8   8.1  4.6
6          Houston Rockets  43  118.4  45.2  78.7  44.5  21.7  14.5   8.6  5.1
7    Oklahoma City Thunder  42  110.7  47.3  79.8  42.9  21.7  13.6   7.6  5.0
8               Miami Heat  43  112.3  46.9  78.3  44.3  26.0  14.9   7.4  4.4
9                Utah Jazz  43  110.9  47.1  77.9  44.9  22.1  15.1   6.1  4.0
10          Indiana Pacers  42  109.6  47.8  78.9  42.5  25.9  13.0   7.2  5.2
11      Philadelphia 76ers  41  110.0  46.6  75.4  45.4  25.8  14.3   8.1  5.4
12        Dallas Mavericks  41  116.7  46.0  77.4  47.2  24.5  12.8   6.2  4.9
13           Brooklyn Nets  32  111.2  44.4  74.7  48.0  24.2  15.3   6.4  4.5
14       Memphis Grizzlies  32  112.7  46.9  76.2  46.3  26.9  15.1   7.9  5.6
15           Orlando Magic  32  107.0  44.4  77.2  44.5  24.2  12.8   8.3  5.6
16  Portland Trail Blazers  32  114.3  46.2  79.9  45.4  20.6  13.0   6.2  6.2
17       San Antonio Spurs  30  113.8  47.1  80.9  44.4  24.7  12.4   7.2  5.5
18            Phoenix Suns  30  112.9  46.5  83.0  43.2  27.1  15.0   7.7  3.9
19    New Orleans Pelicans  29  115.8  46.3  72.4  46.8  26.9  16.3   7.5  4.9
20        Sacramento Kings  29  109.7  46.1  76.8  42.5  23.5  14.3   7.8  4.1
21       Charlotte Hornets  23  102.9  43.4  74.8  42.8  23.8  14.6   6.6  4.1
22      Washington Wizards  24  115.0  46.0  78.6  41.8  25.2  14.1   8.0  4.3
23           Chicago Bulls  22  106.8  44.7  75.5  41.9  23.2  15.5  10.0  4.1
24         New York Knicks  21  105.8  44.7  69.4  46.5  22.1  14.3   7.6  4.7
25         Detroit Pistons  20  107.2  45.9  74.3  41.7  24.1  15.3   7.4  4.5
26           Atlanta Hawks  20  111.8  44.9  79.0  43.3  24.0  16.2   7.8  5.1
27  Minnesota Timberwolves  19  113.3  44.1  75.3  44.8  23.8  15.3   8.7  5.7
28     Cleveland Cavaliers  19  106.9  45.8  75.8  44.2  23.1  16.5   6.9  3.2
29   Golden State Warriors  15  106.3  43.8  80.3  42.8  25.6  14.9   8.2  4.6

In [17]:
df.columns

Index(['Team', 'W', 'PTS', 'FG%', 'FT%', 'REB', 'AST', 'TOV', 'STL', 'BLK'], dtype='object')

In [19]:
df.['Team']

0            Milwaukee Bucks
1         Los Angeles Lakers
2            Toronto Raptors
3                LA Clippers
4             Boston Celtics
5             Denver Nuggets
6            Houston Rockets
7      Oklahoma City Thunder
8                 Miami Heat
9                  Utah Jazz
10            Indiana Pacers
11        Philadelphia 76ers
12          Dallas Mavericks
13             Brooklyn Nets
14         Memphis Grizzlies
15             Orlando Magic
16    Portland Trail Blazers
17         San Antonio Spurs
18              Phoenix Suns
19      New Orleans Pelicans
20          Sacramento Kings
21         Charlotte Hornets
22        Washington Wizards
23             Chicago Bulls
24           New York Knicks
25           Detroit Pistons
26             Atlanta Hawks
27    Minnesota Timberwolves
28       Cleveland Cavaliers
29     Golden State Warriors
Name: Team, dtype: object

In [22]:
df[['Team', 'W']]

                      Team   W
0          Milwaukee Bucks  55
1       Los Angeles Lakers  51
2          Toronto Raptors  49
3              LA Clippers  46
4           Boston Celtics  45
5           Denver Nuggets  45
6          Houston Rockets  43
7    Oklahoma City Thunder  42
8               Miami Heat  43
9                Utah Jazz  43
10          Indiana Pacers  42
11      Philadelphia 76ers  41
12        Dallas Mavericks  41
13           Brooklyn Nets  32
14       Memphis Grizzlies  32
15           Orlando Magic  32
16  Portland Trail Blazers  32
17       San Antonio Spurs  30
18            Phoenix Suns  30
19    New Orleans Pelicans  29
20        Sacramento Kings  29
21       Charlotte Hornets  23
22      Washington Wizards  24
23           Chicago Bulls  22
24         New York Knicks  21
25         Detroit Pistons  20
26           Atlanta Hawks  20
27  Minnesota Timberwolves  19
28     Cleveland Cavaliers  19
29   Golden State Warriors  15

In [23]:
df['Team'][:5]

0       Milwaukee Bucks
1    Los Angeles Lakers
2       Toronto Raptors
3           LA Clippers
4        Boston Celtics
Name: Team, dtype: object

In [25]:
df.iloc[0]

Team    Milwaukee Bucks
W                    55
PTS               118.7
FG%                47.8
FT%                74.5
REB                51.8
AST                25.9
TOV                15.1
STL                 7.3
BLK                   6
Name: 0, dtype: object

In [26]:
df.iloc[:5]

                 Team   W    PTS   FG%   FT%   REB   AST   TOV  STL  BLK
0     Milwaukee Bucks  55  118.7  47.8  74.5  51.8  25.9  15.1  7.3  6.0
1  Los Angeles Lakers  51  113.2  47.9  73.0  45.9  25.4  15.2  8.6  6.7
2     Toronto Raptors  49  112.7  45.8  80.3  45.2  25.3  14.6  8.7  4.9
3         LA Clippers  46  116.2  46.5  79.2  47.7  23.7  14.6  7.0  4.9
4      Boston Celtics  45  113.6  46.1  80.1  45.8  22.7  13.7  8.3  5.6

In [27]:
df.iloc[2,1]

49

In [28]:
df.loc[df['PTS'] > 115]

                    Team   W    PTS   FG%   FT%   REB   AST   TOV  STL  BLK
0        Milwaukee Bucks  55  118.7  47.8  74.5  51.8  25.9  15.1  7.3  6.0
3            LA Clippers  46  116.2  46.5  79.2  47.7  23.7  14.6  7.0  4.9
6        Houston Rockets  43  118.4  45.2  78.7  44.5  21.7  14.5  8.6  5.1
12      Dallas Mavericks  41  116.7  46.0  77.4  47.2  24.5  12.8  6.2  4.9
19  New Orleans Pelicans  29  115.8  46.3  72.4  46.8  26.9  16.3  7.5  4.9

In [30]:
df.loc[(df['PTS'] > 115) & (df['STL'] > 6.5) & (df['W'] < 45)]

                    Team   W    PTS   FG%   FT%   REB   AST   TOV  STL  BLK
6        Houston Rockets  43  118.4  45.2  78.7  44.5  21.7  14.5  8.6  5.1
19  New Orleans Pelicans  29  115.8  46.3  72.4  46.8  26.9  16.3  7.5  4.9

In [31]:
df.loc[df['Team'].str.contains('ets')]

                 Team   W    PTS   FG%   FT%   REB   AST   TOV  STL  BLK
5      Denver Nuggets  45  110.9  47.2  77.6  44.2  26.6  13.8  8.1  4.6
6     Houston Rockets  43  118.4  45.2  78.7  44.5  21.7  14.5  8.6  5.1
13      Brooklyn Nets  32  111.2  44.4  74.7  48.0  24.2  15.3  6.4  4.5
21  Charlotte Hornets  23  102.9  43.4  74.8  42.8  23.8  14.6  6.6  4.1

In [44]:
df.loc[df['Team'] == 'Milwaukee Bucks', 'Team'] = 'Greek Freakers'
df

                      Team   W    PTS   FG%   FT%   REB   AST   TOV   STL  BLK
0           Greek Freakers  55  118.7  47.8  74.5  51.8  25.9  15.1   7.3  6.0
1       Los Angeles Lakers  51  113.2  47.9  73.0  45.9  25.4  15.2   8.6  6.7
2          Toronto Raptors  49  112.7  45.8  80.3  45.2  25.3  14.6   8.7  4.9
3              LA Clippers  46  116.2  46.5  79.2  47.7  23.7  14.6   7.0  4.9
4           Boston Celtics  45  113.6  46.1  80.1  45.8  22.7  13.7   8.3  5.6
5           Denver Nuggets  45  110.9  47.2  77.6  44.2  26.6  13.8   8.1  4.6
6          Houston Rockets  43  118.4  45.2  78.7  44.5  21.7  14.5   8.6  5.1
7    Oklahoma City Thunder  42  110.7  47.3  79.8  42.9  21.7  13.6   7.6  5.0
8               Miami Heat  43  112.3  46.9  78.3  44.3  26.0  14.9   7.4  4.4
9                Utah Jazz  43  110.9  47.1  77.9  44.9  22.1  15.1   6.1  4.0
10          Indiana Pacers  42  109.6  47.8  78.9  42.5  25.9  13.0   7.2  5.2
11      Philadelphia 76ers  41  110.0  46.6  75.4  45.4  25.8  14.3   8.1  5.4
12        Dallas Mavericks  41  116.7  46.0  77.4  47.2  24.5  12.8   6.2  4.9
13           Brooklyn Nets  32  111.2  44.4  74.7  48.0  24.2  15.3   6.4  4.5
14       Memphis Grizzlies  32  112.7  46.9  76.2  46.3  26.9  15.1   7.9  5.6
15           Orlando Magic  32  107.0  44.4  77.2  44.5  24.2  12.8   8.3  5.6
16  Portland Trail Blazers  32  114.3  46.2  79.9  45.4  20.6  13.0   6.2  6.2
17       San Antonio Spurs  30  113.8  47.1  80.9  44.4  24.7  12.4   7.2  5.5
18            Phoenix Suns  30  112.9  46.5  83.0  43.2  27.1  15.0   7.7  3.9
19    New Orleans Pelicans  29  115.8  46.3  72.4  46.8  26.9  16.3   7.5  4.9
20        Sacramento Kings  29  109.7  46.1  76.8  42.5  23.5  14.3   7.8  4.1
21       Charlotte Hornets  23  102.9  43.4  74.8  42.8  23.8  14.6   6.6  4.1
22      Washington Wizards  24  115.0  46.0  78.6  41.8  25.2  14.1   8.0  4.3
23           Chicago Bulls  22  106.8  44.7  75.5  41.9  23.2  15.5  10.0  4.1
24         New York Knicks  21  105.8  44.7  69.4  46.5  22.1  14.3   7.6  4.7
25         Detroit Pistons  20  107.2  45.9  74.3  41.7  24.1  15.3   7.4  4.5
26           Atlanta Hawks  20  111.8  44.9  79.0  43.3  24.0  16.2   7.8  5.1
27  Minnesota Timberwolves  19  113.3  44.1  75.3  44.8  23.8  15.3   8.7  5.7
28     Cleveland Cavaliers  19  106.9  45.8  75.8  44.2  23.1  16.5   6.9  3.2
29   Golden State Warriors  15  106.3  43.8  80.3  42.8  25.6  14.9   8.2  4.6

In [35]:
df.describe()

,W,PTS,FG%,FT%,REB,AST,TOV,STL,BLK
count,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000
mean,33.833333,111.576667,45.980000,77.173333,44.773333,24.343333,14.536667,7.646667,4.910000
std,11.209858,3.870372,1.230475,2.920313,2.204687,1.717192,1.051922,0.876015,0.761283
min,15.000000,102.900000,43.400000,69.400000,41.700000,20.600000,12.400000,6.100000,3.200000
25%,23.250000,109.625000,44.975000,75.325000,42.975000,23.275000,13.875000,7.200000,4.425000
50%,32.000000,112.050000,46.100000,77.500000,44.500000,24.200000,14.600000,7.650000,4.900000
75%,43.000000,113.750000,46.900000,79.150000,45.875000,25.750000,15.175000,8.175000,5.475000
max,55.000000,118.700000,47.900000,83.000000,51.800000,27.100000,16.500000,10.000000,6.700000

In [45]:
df = pd.read_excel('nba_xlsx.xlsx')

In [47]:
df.sort_values('PTS', ascending=False)

                      Team   W    PTS   FG%   FT%   REB   AST   TOV   STL  BLK
0          Milwaukee Bucks  55  118.7  47.8  74.5  51.8  25.9  15.1   7.3  6.0
6          Houston Rockets  43  118.4  45.2  78.7  44.5  21.7  14.5   8.6  5.1
12        Dallas Mavericks  41  116.7  46.0  77.4  47.2  24.5  12.8   6.2  4.9
3              LA Clippers  46  116.2  46.5  79.2  47.7  23.7  14.6   7.0  4.9
19    New Orleans Pelicans  29  115.8  46.3  72.4  46.8  26.9  16.3   7.5  4.9
22      Washington Wizards  24  115.0  46.0  78.6  41.8  25.2  14.1   8.0  4.3
16  Portland Trail Blazers  32  114.3  46.2  79.9  45.4  20.6  13.0   6.2  6.2
17       San Antonio Spurs  30  113.8  47.1  80.9  44.4  24.7  12.4   7.2  5.5
4           Boston Celtics  45  113.6  46.1  80.1  45.8  22.7  13.7   8.3  5.6
27  Minnesota Timberwolves  19  113.3  44.1  75.3  44.8  23.8  15.3   8.7  5.7
1       Los Angeles Lakers  51  113.2  47.9  73.0  45.9  25.4  15.2   8.6  6.7
18            Phoenix Suns  30  112.9  46.5  83.0  43.2  27.1  15.0   7.7  3.9
2          Toronto Raptors  49  112.7  45.8  80.3  45.2  25.3  14.6   8.7  4.9
14       Memphis Grizzlies  32  112.7  46.9  76.2  46.3  26.9  15.1   7.9  5.6
8               Miami Heat  43  112.3  46.9  78.3  44.3  26.0  14.9   7.4  4.4
26           Atlanta Hawks  20  111.8  44.9  79.0  43.3  24.0  16.2   7.8  5.1
13           Brooklyn Nets  32  111.2  44.4  74.7  48.0  24.2  15.3   6.4  4.5
9                Utah Jazz  43  110.9  47.1  77.9  44.9  22.1  15.1   6.1  4.0
5           Denver Nuggets  45  110.9  47.2  77.6  44.2  26.6  13.8   8.1  4.6
7    Oklahoma City Thunder  42  110.7  47.3  79.8  42.9  21.7  13.6   7.6  5.0
11      Philadelphia 76ers  41  110.0  46.6  75.4  45.4  25.8  14.3   8.1  5.4
20        Sacramento Kings  29  109.7  46.1  76.8  42.5  23.5  14.3   7.8  4.1
10          Indiana Pacers  42  109.6  47.8  78.9  42.5  25.9  13.0   7.2  5.2
25         Detroit Pistons  20  107.2  45.9  74.3  41.7  24.1  15.3   7.4  4.5
15           Orlando Magic  32  107.0  44.4  77.2  44.5  24.2  12.8   8.3  5.6
28     Cleveland Cavaliers  19  106.9  45.8  75.8  44.2  23.1  16.5   6.9  3.2
23           Chicago Bulls  22  106.8  44.7  75.5  41.9  23.2  15.5  10.0  4.1
29   Golden State Warriors  15  106.3  43.8  80.3  42.8  25.6  14.9   8.2  4.6
24         New York Knicks  21  105.8  44.7  69.4  46.5  22.1  14.3   7.6  4.7
21       Charlotte Hornets  23  102.9  43.4  74.8  42.8  23.8  14.6   6.6  4.1

In [49]:
df['Total'] = df['REB'] + df['AST'] + df['STL']
df

,Team,W,PTS,FG%,FT%,REB,AST,TOV,STL,BLK,Total
0,Milwaukee Bucks,55,118.7,47.8,74.5,51.8,25.9,15.1,7.3,6.0,85.0
1,Los Angeles Lakers,51,113.2,47.9,73.0,45.9,25.4,15.2,8.6,6.7,79.9
2,Toronto Raptors,49,112.7,45.8,80.3,45.2,25.3,14.6,8.7,4.9,79.2
3,LA Clippers,46,116.2,46.5,79.2,47.7,23.7,14.6,7.0,4.9,78.4
4,Boston Celtics,45,113.6,46.1,80.1,45.8,22.7,13.7,8.3,5.6,76.8
5,Denver Nuggets,45,110.9,47.2,77.6,44.2,26.6,13.8,8.1,4.6,78.9
6,Houston Rockets,43,118.4,45.2,78.7,44.5,21.7,14.5,8.6,5.1,74.8
7,Oklahoma City Thunder,42,110.7,47.3,79.8,42.9,21.7,13.6,7.6,5.0,72.2
8,Miami Heat,43,112.3,46.9,78.3,44.3,26.0,14.9,7.4,4.4,77.7
9,Utah Jazz,43,110.9,47.1,77.9,44.9,22.1,15.1,6.1,4.0,73.1
10,Indiana Pacers,42,109.6,47.8,78.9,42.5,25.9,13.0,7.2,5.2,75.6
11,Philadelphia 76ers,41,110.0,46.6,75.4,45.4,25.8,14.3,8.1,5.4,79.3
12,Dallas Mavericks,41,116.7,46.0,77.4,47.2,24.5,12.8,6.2,4.9,77.9
13,Brooklyn Nets,32,111.2,44.4,74.7,48.0,24.2,15.3,6.4,4.5,78.6
14,Memphis Grizzlies,32,112.7,46.9,76.2,46.3,26.9,15.1,7.9,5.6,81.1
15,Orlando Magic,32,107.0,44.4,77.2,44.5,24.2,12.8,8.3,5.6,77.0
16,Portland Trail Blazers,32,114.3,46.2,79.9,45.4,20.6,13.0,6.2,6.2,72.2
17,San Antonio Spurs,30,113.8,47.1,80.9,44.4,24.7,12.4,7.2,5.5,76.3
18,Phoenix Suns,30,112.9,46.5,83.0,43.2,27.1,15.0,7.7,3.9,78.0
19,New Orleans Pelicans,29,115.8,46.3,72.4,46.8,26.9,16.3,7.5,4.9,81.2
20,Sacramento Kings,29,109.7,46.1,76.8,42.5,23.5,14.3,7.8,4.1,73.8
21,Charlotte Hornets,23,102.9,43.4,74.8,42.8,23.8,14.6,6.6,4.1,73.2
22,Washington Wizards,24,115.0,46.0,78.6,41.8,25.2,14.1,8.0,4.3,75.0
23,Chicago Bulls,22,106.8,44.7,75.5,41.9,23.2,15.5,10.0,4.1,75.1
24,New York Knicks,21,105.8,44.7,69.4,46.5,22.1,14.3,7.6,4.7,76.2
25,Detroit Pistons,20,107.2,45.9,74.3,41.7,24.1,15.3,7.4,4.5,73.2
26,Atlanta Hawks,20,111.8,44.9,79.0,43.3,24.0,16.2,7.8,5.1,75.1
27,Minnesota Timberwolves,19,113.3,44.1,75.3,44.8,23.8,15.3,8.7,5.7,77.3
28,Cleveland Cavaliers,19,106.9,45.8,75.8,44.2,23.1,16.5,6.9,3.2,74.2
29,Golden State Warriors,15,106.3,43.8,80.3,42.8,25.6,14.9,8.2,4.6,76.6

In [50]:
df.drop(columns = ['Total'])

                      Team   W    PTS   FG%   FT%   REB   AST   TOV   STL  BLK
0          Milwaukee Bucks  55  118.7  47.8  74.5  51.8  25.9  15.1   7.3  6.0
1       Los Angeles Lakers  51  113.2  47.9  73.0  45.9  25.4  15.2   8.6  6.7
2          Toronto Raptors  49  112.7  45.8  80.3  45.2  25.3  14.6   8.7  4.9
3              LA Clippers  46  116.2  46.5  79.2  47.7  23.7  14.6   7.0  4.9
4           Boston Celtics  45  113.6  46.1  80.1  45.8  22.7  13.7   8.3  5.6
5           Denver Nuggets  45  110.9  47.2  77.6  44.2  26.6  13.8   8.1  4.6
6          Houston Rockets  43  118.4  45.2  78.7  44.5  21.7  14.5   8.6  5.1
7    Oklahoma City Thunder  42  110.7  47.3  79.8  42.9  21.7  13.6   7.6  5.0
8               Miami Heat  43  112.3  46.9  78.3  44.3  26.0  14.9   7.4  4.4
9                Utah Jazz  43  110.9  47.1  77.9  44.9  22.1  15.1   6.1  4.0
10          Indiana Pacers  42  109.6  47.8  78.9  42.5  25.9  13.0   7.2  5.2
11      Philadelphia 76ers  41  110.0  46.6  75.4  45.4  25.8  14.3   8.1  5.4
12        Dallas Mavericks  41  116.7  46.0  77.4  47.2  24.5  12.8   6.2  4.9
13           Brooklyn Nets  32  111.2  44.4  74.7  48.0  24.2  15.3   6.4  4.5
14       Memphis Grizzlies  32  112.7  46.9  76.2  46.3  26.9  15.1   7.9  5.6
15           Orlando Magic  32  107.0  44.4  77.2  44.5  24.2  12.8   8.3  5.6
16  Portland Trail Blazers  32  114.3  46.2  79.9  45.4  20.6  13.0   6.2  6.2
17       San Antonio Spurs  30  113.8  47.1  80.9  44.4  24.7  12.4   7.2  5.5
18            Phoenix Suns  30  112.9  46.5  83.0  43.2  27.1  15.0   7.7  3.9
19    New Orleans Pelicans  29  115.8  46.3  72.4  46.8  26.9  16.3   7.5  4.9
20        Sacramento Kings  29  109.7  46.1  76.8  42.5  23.5  14.3   7.8  4.1
21       Charlotte Hornets  23  102.9  43.4  74.8  42.8  23.8  14.6   6.6  4.1
22      Washington Wizards  24  115.0  46.0  78.6  41.8  25.2  14.1   8.0  4.3
23           Chicago Bulls  22  106.8  44.7  75.5  41.9  23.2  15.5  10.0  4.1
24         New York Knicks  21  105.8  44.7  69.4  46.5  22.1  14.3   7.6  4.7
25         Detroit Pistons  20  107.2  45.9  74.3  41.7  24.1  15.3   7.4  4.5
26           Atlanta Hawks  20  111.8  44.9  79.0  43.3  24.0  16.2   7.8  5.1
27  Minnesota Timberwolves  19  113.3  44.1  75.3  44.8  23.8  15.3   8.7  5.7
28     Cleveland Cavaliers  19  106.9  45.8  75.8  44.2  23.1  16.5   6.9  3.2
29   Golden State Warriors  15  106.3  43.8  80.3  42.8  25.6  14.9   8.2  4.6

In [51]:
df.groupby(['REB']).mean()

         W     PTS    FG%    FT%    AST    TOV    STL   BLK  Total
REB
41.7  20.0  107.20  45.90  74.30  24.10  15.30   7.40  4.50  73.20
41.8  24.0  115.00  46.00  78.60  25.20  14.10   8.00  4.30  75.00
41.9  22.0  106.80  44.70  75.50  23.20  15.50  10.00  4.10  75.10
42.5  35.5  109.65  46.95  77.85  24.70  13.65   7.50  4.65  74.70
42.8  19.0  104.60  43.60  77.55  24.70  14.75   7.40  4.35  74.90
42.9  42.0  110.70  47.30  79.80  21.70  13.60   7.60  5.00  72.20
43.2  30.0  112.90  46.50  83.00  27.10  15.00   7.70  3.90  78.00
43.3  20.0  111.80  44.90  79.00  24.00  16.20   7.80  5.10  75.10
44.2  32.0  108.90  46.50  76.70  24.85  15.15   7.50  3.90  76.55
44.3  43.0  112.30  46.90  78.30  26.00  14.90   7.40  4.40  77.70
44.4  30.0  113.80  47.10  80.90  24.70  12.40   7.20  5.50  76.30
44.5  37.5  112.70  44.80  77.95  22.95  13.65   8.45  5.35  75.90
44.8  19.0  113.30  44.10  75.30  23.80  15.30   8.70  5.70  77.30
44.9  43.0  110.90  47.10  77.90  22.10  15.10   6.10  4.00  73.10
45.2  49.0  112.70  45.80  80.30  25.30  14.60   8.70  4.90  79.20
45.4  36.5  112.15  46.40  77.65  23.20  13.65   7.15  5.80  75.75
45.8  45.0  113.60  46.10  80.10  22.70  13.70   8.30  5.60  76.80
45.9  51.0  113.20  47.90  73.00  25.40  15.20   8.60  6.70  79.90
46.3  32.0  112.70  46.90  76.20  26.90  15.10   7.90  5.60  81.10
46.5  21.0  105.80  44.70  69.40  22.10  14.30   7.60  4.70  76.20
46.8  29.0  115.80  46.30  72.40  26.90  16.30   7.50  4.90  81.20
47.2  41.0  116.70  46.00  77.40  24.50  12.80   6.20  4.90  77.90
47.7  46.0  116.20  46.50  79.20  23.70  14.60   7.00  4.90  78.40
48.0  32.0  111.20  44.40  74.70  24.20  15.30   6.40  4.50  78.60
51.8  55.0  118.70  47.80  74.50  25.90  15.10   7.30  6.00  85.00

In [66]:
df = pd.read_excel('nba_xlsx.xlsx')
df.sort_values('W', ascending=False)

,Team,Specialty,W,PTS,FG%,FT%,REB,AST,TOV,STL,BLK
29,Milwaukee Bucks,Both,55,118.7,47.8,74.5,51.8,25.9,15.1,7.3,6.0
19,Los Angeles Lakers,Defenders,51,113.2,47.9,73.0,45.9,25.4,15.2,8.6,6.7
16,Toronto Raptors,Defenders,49,112.7,45.8,80.3,45.2,25.3,14.6,8.7,4.9
26,LA Clippers,Both,46,116.2,46.5,79.2,47.7,23.7,14.6,7.0,4.9
11,Denver Nuggets,Neither,45,110.9,47.2,77.6,44.2,26.6,13.8,8.1,4.6
21,Boston Celtics,Defenders,45,113.6,46.1,80.1,45.8,22.7,13.7,8.3,5.6
28,Houston Rockets,Shooters,43,118.4,45.2,78.7,44.5,21.7,14.5,8.6,5.1
12,Utah Jazz,Defenders,43,110.9,47.1,77.9,44.9,22.1,15.1,6.1,4.0
15,Miami Heat,Neither,43,112.3,46.9,78.3,44.3,26.0,14.9,7.4,4.4
7,Indiana Pacers,Defenders,42,109.6,47.8,78.9,42.5,25.9,13.0,7.2,5.2
10,Oklahoma City Thunder,Defenders,42,110.7,47.3,79.8,42.9,21.7,13.6,7.6,5.0
9,Philadelphia 76ers,Defenders,41,110.0,46.6,75.4,45.4,25.8,14.3,8.1,5.4
27,Dallas Mavericks,Shooters,41,116.7,46.0,77.4,47.2,24.5,12.8,6.2,4.9
17,Memphis Grizzlies,Shooters,32,112.7,46.9,76.2,46.3,26.9,15.1,7.9,5.6
23,Portland Trail Blazers,Shooters,32,114.3,46.2,79.9,45.4,20.6,13.0,6.2,6.2
5,Orlando Magic,Defenders,32,107.0,44.4,77.2,44.5,24.2,12.8,8.3,5.6
13,Brooklyn Nets,Defenders,32,111.2,44.4,74.7,48.0,24.2,15.3,6.4,4.5
18,Phoenix Suns,Shooters,30,112.9,46.5,83.0,43.2,27.1,15.0,7.7,3.9
22,San Antonio Spurs,Shooters,30,113.8,47.1,80.9,44.4,24.7,12.4,7.2,5.5
25,New Orleans Pelicans,Shooters,29,115.8,46.3,72.4,46.8,26.9,16.3,7.5,4.9
8,Sacramento Kings,Neither,29,109.7,46.1,76.8,42.5,23.5,14.3,7.8,4.1
24,Washington Wizards,Shooters,24,115.0,46.0,78.6,41.8,25.2,14.1,8.0,4.3
0,Charlotte Hornets,Neither,23,102.9,43.4,74.8,42.8,23.8,14.6,6.6,4.1
3,Chicago Bulls,Neither,22,106.8,44.7,75.5,41.9,23.2,15.5,10.0,4.1
1,New York Knicks,Neither,21,105.8,44.7,69.4,46.5,22.1,14.3,7.6,4.7
6,Detroit Pistons,Neither,20,107.2,45.9,74.3,41.7,24.1,15.3,7.4,4.5
14,Atlanta Hawks,Neither,20,111.8,44.9,79.0,43.3,24.0,16.2,7.8,5.1
20,Minnesota Timberwolves,Shooters,19,113.3,44.1,75.3,44.8,23.8,15.3,8.7,5.7
4,Cleveland Cavaliers,Neither,19,106.9,45.8,75.8,44.2,23.1,16.5,6.9,3.2
2,Golden State Warriors,Neither,15,106.3,43.8,80.3,42.8,25.6,14.9,8.2,4.6

In [63]:
df.groupby(['Specialty']).sum()

             W     PTS    FG%    FT%    REB    AST    TOV   STL   BLK
Specialty
Both       101   234.9   94.3  153.7   99.5   49.6   29.7  14.3  10.9
Defenders  377   998.9  417.4  697.3  405.1  217.3  127.6  69.3  46.9
Neither    257  1080.6  453.4  761.8  434.2  242.0  150.3  77.8  43.4
Shooters   280  1032.9  414.3  702.4  404.4  221.4  128.5  68.0  46.1

In [67]:
df.groupby(['Specialty']).mean()

,W,PTS,FG%,FT%,REB,AST,TOV,STL,BLK
Specialty,,,,,,,,,
Both,50.500000,117.450000,47.150000,76.850000,49.750000,24.800000,14.850000,7.150000,5.450000
Defenders,41.888889,110.988889,46.377778,77.477778,45.011111,24.144444,14.177778,7.700000,5.211111
Neither,25.700000,108.060000,45.340000,76.180000,43.420000,24.200000,15.030000,7.780000,4.340000
Shooters,31.111111,114.766667,46.033333,78.044444,44.933333,24.600000,14.277778,7.555556,5.122222

In [69]:
df.to_csv('with_index.xlsx')